# Generated by Django 5.0.2 on 2024-02-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('guest_number', models.IntegerField()),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
